-- Add missing columns to Trade table
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "closeDate" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "entryDate" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "closePrice" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "entryPrice" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "instrument" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "accountNumber" TEXT DEFAULT '';
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "pnl" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "timeInPosition" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "public"."Trade" ADD COLUMN IF NOT EXISTS "quantity" INTEGER DEFAULT 0;
